class PhoneBook:
    """A simple phone book application for storing and managing contacts."""
    def __init__(self):
         """Initializes the phone book with an empty dictionary to store contacts."""
          self.contacts = {}  # Dictionary to store contacts (name: phone number)

    def add_contact(self, name, phone_number):
        """Adds a new contact to the phone book. Args:
                                                                                        name (str): The name of the contact.
                                                                                                    phone_number (str): The phone number of the contact.
                                                                                                            """
                                                                                                                    if name in self.contacts:
                                                                                                                                print(f"Contact '{name}' already exists.  Use update_contact to modify.")
                                                                                                                                            return

                                                                                                                                                    self.contacts[name] = phone_number
                                                                                                                                                            print(f"Contact '{name}' added successfully.")

                                                                                                                                                                def update_contact(self, name, new_phone_number):
                                                                                                                                                                        """
                                                                                                                                                                                Updates an existing contact's phone number.

                                                                                                                                                                                        Args:
                                                                                                                                                                                                    name (str): The name of the contact to update.
                                                                                                                                                                                                                new_phone_number (str): The new phone number for the contact.
                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                if name not in self.contacts:
                                                                                                                                                                                                                                            print(f"Contact '{name}' not found.  Use add_contact to add it.")
                                                                                                                                                                                                                                                        return

                                                                                                                                                                                                                                                                self.contacts[name] = new_phone_number
                                                                                                                                                                                                                                                                        print(f"Contact '{name}' updated successfully.")

                                                                                                                                                                                                                                                                            def delete_contact(self, name):
                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                            Deletes a contact from the phone book.

                                                                                                                                                                                                                                                                                                    Args:
                                                                                                                                                                                                                                                                                                                name (str): The name of the contact to delete.
                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                if name in self.contacts:
                                                                                                                                                                                                                                                                                                                                            del self.contacts[name]
                                                                                                                                                                                                                                                                                                                                                        print(f"Contact '{name}' deleted successfully.")
                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                            print(f"Contact '{name}' not found.")

                                                                                                                                                                                                                                                                                                                                                                                def list_contacts(self):
                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                Lists all contacts in the phone book.
                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                if not self.contacts:
                                                                                                                                                                                                                                                                                                                                                                                                                            print("Phone book is empty.")
                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Contacts:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            for name, phone_number in self.contacts.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Name: {name}, Phone: {phone_number}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def search_contact(self, name):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Searches for a contact by name and displays their phone number.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Args:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name (str): The name of the contact to search for.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if name in self.contacts:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Name: {name}, Phone: {self.contacts[name]}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Contact '{name}' not found.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Example usage:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        phone_book = PhoneBook()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\nPhone Book Menu:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("1. Add Contact")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("2. Update Contact")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("3. Delete Contact")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("4. List Contacts")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("5. Search Contact")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("6. Quit")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            choice = input("Enter your choice: ")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if choice == '1':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name = input("Enter contact name: ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            phone = input("Enter phone number: ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        phone_book.add_contact(name, phone)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '2':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name = input("Enter name of contact to update: ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new_phone = input("Enter new phone number: ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    phone_book.update_contact(name, new_phone)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif choice == '3':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name = input("Enter name of contact to delete: ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    phone_book.delete_contact(name)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif choice == '4':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        phone_book.list_contacts()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '5':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name = input("Enter name to search: ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        phone_book.search_contact(name)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif choice == '6':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Exiting phone book.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Invalid choice. Please try again.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )")))"))"))")
